Repository marcosdosea/gcm-ufs, pull requests merged in 2020-11, with the labels that each got.

#231 Resolved #223 - adiçao do atributo CPF na classe GerenciadoraCliente
  LuizMoitinho/GerenciadoraCliente.java
Labels: enhancement

#232 #222 - criação do método para retornar os dados da classe em JSON
  LuizMoitinho/GerenciadoraVenda.java
Labels: good first issue

#289 Método alterarCliente() adicionado.
  Andeson/Cliente.java
Labels: enhancement

#290 Corrigido o problema da data fixa
  Andeson/Cliente.java
Labels: bug
