Repository marcosdosea/gcm-ufs, pull requests merged in 2022-07, with the labels that each got.

#514 501 Criar a Classe GerenciadorVenda com pelo chama pelo menos um método de GerenciadorCliente
  Kevenny/GerenciadorCliente.java
  Kevenny/GerenciadorVenda.java
Labels: feature

#512 500 Adicionar na classe GerenciadorCliente métodos remover e alterar
  Kevenny/GerenciadorCliente.java
Labels: feature

#805 Branch ericles
  Ericles/Readme.md
Labels: feature

#814 Lauro_Metodos adicionados Resolve #811
  Lauro/GerenciadorCliente.java
Labels: feature

#816 Lauro_Metodo adicionado Resolve #813
  Lauro/GerenciadorVenda.java
Labels: feature

#888 Classe GerenciadorCliente e métodos inserir e consultar adicionados. …
  Reinan/GerenciadorCliente.java
Labels: enhancement

#869 Add:: classe GerenciadorCliente com método de inserir e consultar
  Ericles/GerenciadorCliente.cs
Labels: feature

#890 Métodos remover e alterar adicionados na classe GerenciadorCliente. r…
  Reinan/GerenciadorCliente.java
Labels: enhancement

#891 Chamada do método remover na classe GerenciadorVendas.java. resolve #886
  Reinan/GerenciadorVendas.java
Labels: enhancement

#892 Revert "Chamada do método remover na classe GerenciadorVendas.java. resolve #886"
  Reinan/GerenciadorVendas.java
Labels: enhancement

#899 Criando pasta Joanne #898
  Joanne/ReadMe.md
Labels: good first issue

#870 Add:: Adicionar na classe GerenciadorCliente métodos remover e alterar
  Ericles/GerenciadorCliente.cs
Labels: feature

#911 Add: GerenciarCliente
  Joanne/GerenciarCliente.py
Labels: feature

#871 ADD:: Criar a Classe GerenciadorVenda com pelo chama pelo menos um método de GerenciadorCliente
  Ericles/GerenciadorVenda.cs
Labels: feature

#916 Classe GerenciadorVenda implementada.
  Thiago/GerenciadorCliente.java
  Thiago/GerenciadorVenda.java
Labels: feature

#915 Add: Gerenciar Cliente com metodos remover e alterar cliente
  Joanne/GerenciarCliente.py
Labels: enhancement, feature

#921 Add: metodos remover e alterar
  Joanne/GerenciarCliente.py
Labels: enhancement

#923 Add: Classe GerenciadorVenda
  Joanne/GerenciarVenda.py
Labels: enhancement, feature

#878 Pull Request resolve #875
  Charles/GerenciadorCliente.java
Labels: feature

#928 Fix: Faltou usar a chamada de método da classe GerenciadorCliente.
  Ericles/GerenciadorVenda.cs
Labels: enhancement
